# This task packages and installs the external chaincode details
- name: Package and installs the external chaincode details
  include_tasks: nested_main.yaml
  vars:
    chaincode_name: "{{ peer.chaincode.name | lower }}"
    chaincode_version: "{{ peer.chaincode.version }}"
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer
  when: 
    - peer.chaincode is defined
    - peer.chaincode.external_chaincode is defined
    - peer.chaincode.external_chaincode == true  
