#############################################################################################
# This role creates the value file for peers of organisations and write couch db credentials
# to the vault.
#############################################################################################

# Create the value file for peers of organisations 
- name: This role creates the value file for peers of organisations 
  include_tasks: nested_main.yaml
  loop: "{{ component_services.peers }}"
  loop_control:
    loop_var: peer 
