############################################################################################
# This task fetches current core.yaml from running peers
- name: Fetch current core.yaml from running peers 
  shell: |
    export POD_NAME=$(KUBECONFIG={{ kubernetes.config_file }} kubectl get po -n {{ component_name }} | grep "{{ orderer.name }}" | awk '{print $1}')
    KUBECONFIG={{ kubernetes.config_file }} kubectl cp {{ component_name }}/${POD_NAME}:/etc/hyperledger/fabric/orderer.yaml ../../../build/{{ orderer.name }}-orderer.yaml
  loop_control:
    loop_var: orderer
  loop: "{{ component_services.orderers }}"
