############################################################################################
# This task fails the deployment if no commit indicator is found
# - name: Fail the deployment because no commit indicator is found
#   fail:
#     msg: "No commit indicators is found, {'committedpeer': {'orgnamespace': 'chaincodename-version'}}"
#   when: committedpeer is not defined or committedpeer.keys() | length == 0

# This task check committed chaincode pods for all channels
- name: Commit chaincode
  include_tasks: wait_for_commit_sub.yaml
  vars:
    participants: "{{ channel.participants }}"
  loop: "{{ network['channels'] }}"
  loop_control:
    loop_var: channel  
  when: add_new_org == 'false' and '2.' in network.version

# This task deploys the external chaincode server
- name: Deploy the external chaincode server
  include_tasks: nested_main.yaml
  vars:
    chaincode_name: "{{ peer.chaincode.name | lower }}"
    chaincode_version: "{{ peer.chaincode.version }}"
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer
    extended: true
  when: 
    - peer.chaincode is defined
    - peer.chaincode.external_chaincode is defined
    - peer.chaincode.external_chaincode == true
