---
# This task only check for the first peer of the first creator listed
# TODO: multi-version support
- name: "Waiting for chaincode to be commited on {{ peer.name }}"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    channelcreator_query: "participants[?type=='creator']"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    peer: "{{ org.services.peers | first}}"
    commit_peer_name: "{{['name']}}"
    component_type: "Job"
    namespace: "{{ org.name | lower }}-net"
    component_name: "commitchaincode-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}-{{ peer.chaincode.sequence }}"
  loop: "{{ (channel | json_query(channelcreator_query))[0:1] }}"
  loop_control:
    loop_var: participant 
  when: 
    - peer.chaincode is defined and '2.' in network.version
