# This task creates certs for chaincode server
- name: Creates certs for chaincode server
  include_tasks: nested_main.yaml
  loop: "{{ services.peers }}"
  loop_control:
    loop_var: peer
  when: 
    - peer.chaincode is defined
    - peer.chaincode.external_chaincode is defined
    - peer.chaincode.external_chaincode == true  
    - peer.chaincode.tls_disabled == false
