############################################################################################
# This task creates valuefiles for the cli of first peer creator organization
# Creates the CLI and to fetch the latest configuration block to add new config details
############################################################################################

# checking for fabric cli
- name: "Check if fabric cli is already present"
  k8s_info:
    kind: Pod
    namespace: "{{ org.name }}-net"
    kubeconfig: "{{ org.k8s.config_file }}"
    context: "{{ org.k8s.context }}"
    label_selectors:
      - app = cli
  register: existing_cli

- debug:
    var: existing_cli

# Create the value file for org first peer
- name: "create cli value files for {{peer.name}}-{{ org.name }} for signing the modified configuration block"
  include_role:
    name: k8_component
  vars:
    component_type_name: "{{ participantx.name }}"
    component_type: "existing_peer_cli_job"    
    component_name: "cli-{{ channel_name }}-{{ participantx.name }}-{{ peer.name }}"
    peer_name: "{{ peer.name }}"
    component_ns: "{{ participantx.name | lower}}-net"
    vault: "{{ org.vault }}"
    fabrictools_image: "hyperledger/fabric-tools:{{ network.version }}"
    alpine_image: "{{ docker_url }}/alpine-utils:1.0"
    channel_name: "{{ channel_name }}"
    storage_class: "{{ participantx.name }}sc"
    release_dir: "./build"
    participant: "{{ participantx }}"
  when: existing_cli.resources|length == 0

# Creeate the value file for creater org first peer
- name: "start cli"
  shell: |
    KUBECONFIG={{ org.k8s.config_file }} helm upgrade --install -f {{playbook_dir}}/../../../{{org.gitops.release_dir}}/{{ participantx.name }}/existing_peer_cli_job.yaml {{ peer.name }}-{{ participantx.name }}-cli {{playbook_dir}}/../../../{{org.gitops.chart_source}}/fabric_cli
  when: existing_cli.resources|length == 0

# waiting for fabric cli
- name: "Check if fabric cli is present"
  k8s_info:
    kind: Pod
    namespace: "{{ org.name }}-net"
    kubeconfig: "{{ org.k8s.config_file }}"
    context: "{{ org.k8s.context }}"
    label_selectors:
      - app = cli
  register: get_cli
  until: ("Running" in get_cli|json_query('resources[*].status.phase'))
  retries: "{{ network.env.retry_count}}"
  delay: 40

############################################################################################
# This task fetch the config block from blockchain, convert it to JSON and copy to build folder
- name: fetch and copy the configuration block from the blockchain to build folder
  shell: |
    export PEER_CLI=$(KUBECONFIG={{ org.k8s.config_file }} kubectl get po -n {{ org.name }}-net | grep "cli" | head -n 1 | awk '{print $1}')
    KUBECONFIG={{ kubernetes.config_file }} kubectl exec -n {{ org.name }}-net ${PEER_CLI} -- peer channel fetch config {{ channel_name }}_config_block.pb -o {{ participantx.ordererAddress }} -c {{ channel_name }} --tls --cafile ${ORDERER_CA}
    KUBECONFIG={{ kubernetes.config_file }} kubectl exec -n {{ org.name }}-net ${PEER_CLI} -- configtxlator proto_decode --input {{ channel_name }}_config_block.pb --type common.Block --output {{ channel_name }}_config.json
    KUBECONFIG={{ kubernetes.config_file }} kubectl exec -n {{ org.name }}-net ${PEER_CLI} -- jq .data.data[0].payload.data.config {{ channel_name }}_config.json > ../../../build/{{ channel_name }}_config.json
  environment:
    ORDERER_CA: "/opt/gopath/src/github.com/hyperledger/fabric/crypto/orderer/tls/ca.crt"
  vars: 
    kubernetes: "{{ org.k8s }}"
