{{- if $.Values.service.ports.metrics.enabled }}
{{- if $.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ $.Values.peer.name }}
    walmart.com/prometheus: infrastructure
  name: {{ $.Values.peer.name }}
  namespace:  {{ $.Values.metadata.namespace }}
spec:
  jobLabel: {{ .Release.Name }}
  endpoints:
    - honorLabels: true
      port: metrics
  namespaceSelector:
    matchNames:
      -  {{ $.Values.metadata.namespace }}
  selector:
    matchLabels:
      run: {{ $.Values.peer.name }}
      app.kubernetes.io/instance: {{ .Release.Name }} 
{{- end }}
{{- end }}
