# This playbook deploys the blockchain platform components.
# The DLT network should already be created using the same configuration file as that
#   used for running this playbook.
---
# This will apply to ansible_provisioners. /etc/ansible/hosts should be configured with this group
- hosts: ansible_provisioners
  gather_facts: no
  tasks:
    ############################################################################################
    # Create restserver value file for the peer nodes
    - include_role:
        name: "create/hlf-rest-client"
      vars:
        component_name: "hlf-rest-client"
        component_ns: "{{ organization_data.name | lower }}-net"
        component_type: "{{ organization_data.type | lower }}"
        component_gitops: "{{ organization_data.gitops }}"
        component_vault: "{{ organization_data.vault }}"
        values_dir: "{{ playbook_dir }}/../../{{ organization_data.gitops.release_dir }}/{{ organization_data.name | lower }}"
      loop: "{{ network['organizations'] }}"
      loop_control:
        loop_var: organization_data
      when: network['type'] == 'fabric'
