###########################################################################################
# This task calls nested_fetch_role to generate the cli value files for first peer of organization
# Create cli to get config block and add new organization configuration to it
############################################################################################

# Start the cli, submit configuration block envelope
- name: Call nested_fetch_role for the peer
  include_tasks: nested_update.yaml
  vars:
    channel_name: "{{ item.channel_name | lower }}"
    org_query: "organizations[?name=='{{participantx.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    peer: "{{ participantx.peers | first }}"    
    component_type: "{{ participantx.type }}"
    os: "{{ fabric.os }}"
    arch: "{{ fabric.arch }}"
    version: "{{ network.version }}"
  loop: "{{ participants }}"
  loop_control:
    loop_var: participantx
  when: participantx.type == 'creator'
