---
#######################################
# Playbook to setup the environment for running the Blockchain Automation Framework configurations
#  - checks and installs kubectl, helm and vault clients
#  - If cloud platform is AWS, checks and installs aws-cli and aws-authenticator
#######################################
  - hosts: ansible_provisioners
    gather_facts: yes
    tasks:
    - include_role:
        name:  setup/kubectl
      vars:
        kubectl:
          version: "1.16.13"
          os: "{{ install_os }}"
          arch: "{{ install_arch }}"
          bin_directory: "{{ bin_install_dir }}"
          checksum: "sha256:170bee26f53829c8917fad343fd10b0b9bcd47dc296c14604b6b28e6c3cec08c"
      with_items: "{{ network.organizations }}"
    - include_role:
        name:  setup/helm
      vars:
        helm:
          version: "v3.2.4"
          os: "{{ install_os }}"
          arch: "{{ install_arch }}"
          bin_directory: "{{ bin_install_dir }}"
          checksum: ""
      with_items: "{{ network.organizations }}"
    - include_role:
        name:  setup/vault
      vars:
        vault:
          version: "1.0.1"
          os: "{{ install_os }}"
          arch: "{{ install_arch }}"
          bin_directory: "{{ bin_install_dir }}"
          checksum: ""
        with_items: "{{ network.organizations }}"
    vars: #These variables can be overriden from the command line
      privilege_escalate: false           #Default to NOT escalate to root privledges
      install_os: "linux"                 #Default to linux OS
      install_arch:  "amd64"              #Default to amd64 architecture
      bin_install_dir:  "~/bin"           #Default to ~/bin install directory for binaries
